apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backsharedgroceries.fullname" . }}-secret
  labels:
    {{- include "backsharedgroceries.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_CN_STR: {{ .Values.secrets.DB_CN_STR | quote }}
  JWT_KEY: {{ .Values.secrets.JWT_KEY | quote }}
