replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  JWT_ISSUER: sharedgroceries
  JWT_AUDIENCE: sharedgroceries-clients

secrets:
  DB_CN_STR: ""
  JWT_KEY: ""

probes:
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
  startup:
    path: /health
    failureThreshold: 30
    periodSeconds: 5

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

podDisruptionBudget:
  enabled: true
  minAvailable: 1
